### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by vanhyr** [xudaolong/memos-desktop#9]
## Summary

Is there a new release planned for custom server url support?

**Comment by baduyifei** [comment]
https://github.com/xudaolong/memos-desktop/issues/4

**Comment by baduyifei** [comment]
https://github.com/xudaolong/memos-desktop/issues/4  it can be connected, here is the solution

**Comment by baduyifei** [comment]
https://github.com/xudaolong/memos-desktop/issues/4#issuecomment-1695185685
It can support custom servers, here is the solution

**Comment by vanhyr** [comment]
Thank you, that was helpful, although a little sketchy

**Comment by vanhyr** [comment]
Thank you, that was helpful, although a little sketchy
